#!/bin/bash
echo "=== PPROF Test ==="
echo "1. Запусти сервис:"
echo "   export PPROF_ENABLED=true"
echo "   export PPROF_PORT=6060"
echo "   go run cmd/main.go"
echo ""
echo "2. В другом терминале:"
echo "   curl http://localhost:6060/debug/pprof/"
echo ""
echo "3. Снять профиль CPU на 30 секунд:"
echo "   curl -o cpu.pprof 'http://localhost:6060/debug/pprof/profile?seconds=30'"
echo ""
echo "4. Снять профиль памяти:"
echo "   curl -o heap.pprof http://localhost:6060/debug/pprof/heap"
echo ""
echo "5. Анализ:"
echo "   go tool pprof -http=:8081 cpu.pprof"
echo "   go tool pprof -http=:8082 heap.pprof"
